//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace find_my_pdf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"CREATE TABLE IF NOT EXISTS pdfs ([id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, pdf_path nvarchar(200) NOT NULL UNIQUE, pdf_text_content nvarchar(2000), pdf_file_name nvarchar(150), pdf_keyword nvarchar(300), status varchar(50), created_at datetime, updated_at datetime)")]
        public string CREATE_PDF_TABLE {
            get {
                return ((string)(this["CREATE_PDF_TABLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO pdfs (pdf_path, pdf_text_content, pdf_file_name, pdf_keyword, status," +
            " created_at, updated_at) VALUES (\'{0}\', \'{1}\', \'{2}\', \'{3}\', \'OK\', \'{4}\', \'{5}\')" +
            ";")]
        public string PDF_INSERT_NEW {
            get {
                return ((string)(this["PDF_INSERT_NEW"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO pdfs (pdf_path, pdf_text_content, pdf_file_name, pdf_keyword, status," +
            " created_at, updated_at) VALUES ")]
        public string PDF_INSERT_ {
            get {
                return ((string)(this["PDF_INSERT_"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(\'{0}\', \'{1}\', \'{2}\', \'{3}\', \'OK\', \'{4}\', \'{5}\')")]
        public string PDF_VALUES {
            get {
                return ((string)(this["PDF_VALUES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) as total FROM pdfs")]
        public string PDF_COUNTER {
            get {
                return ((string)(this["PDF_COUNTER"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tìm kiếm file PDF - có [{0}] file PDF")]
        public string LBL_BTN_QUET {
            get {
                return ((string)(this["LBL_BTN_QUET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT pdf_path, pdf_text_content, status FROM pdfs WHERE pdf_text_content LIKE \'" +
            "%{0}%\';")]
        public string PDF_SEARCH {
            get {
                return ((string)(this["PDF_SEARCH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CREATE TABLE IF NOT EXISTS search_history ([id] INTEGER NOT NULL PRIMARY KEY AUTO" +
            "INCREMENT, search_text nvarchar(200) NOT NULL UNIQUE, created_at datetime)")]
        public string CREATE_HISTORY_TABLE {
            get {
                return ((string)(this["CREATE_HISTORY_TABLE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT search_text FROM search_history ORDER BY created_at DESC LIMIT 20;")]
        public string LAST_TEN_HISTORIES {
            get {
                return ((string)(this["LAST_TEN_HISTORIES"]));
            }
        }
    }
}
